// <auto-generated />
using System;
using MessageBoard;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageBoard.Migrations
{
    [DbContext(typeof(DbPostDataContext))]
    partial class DbPostDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MessageBoard.CommentMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .IsRequired();

                    b.Property<int?>("PostMessageId");

                    b.HasKey("Id");

                    b.HasIndex("PostMessageId");

                    b.ToTable("CommentMessage");
                });

            modelBuilder.Entity("MessageBoard.PostMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .IsRequired();

                    b.Property<int>("Total_Likes");

                    b.HasKey("Id");

                    b.ToTable("postMessage");
                });

            modelBuilder.Entity("MessageBoard.CommentMessage", b =>
                {
                    b.HasOne("MessageBoard.PostMessage")
                        .WithMany("Comment")
                        .HasForeignKey("PostMessageId");
                });
#pragma warning restore 612, 618
        }
    }
}
